<template>
    <div class="text text-white">
      <h1 class="text-4xl font-medium">抱歉</h1>
      <p class="text-2xl">该站点还在施工</p>
      <p class="text-2xl">所以你还无法访问</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
      <h1 class="text-4xl font-medium">测试</h1>
      <p class="text-2xl">你好这是一个测试文本</p>
    </div>
</template>
